import { FilePlus2, LogOut, Pencil, Save, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import ThemeToggle from "../components/ThemeToggle";
import { setPageSeo } from "../lib/seo";

type Post = { slug: string; sha?: string; title: string; date: string; category: string; readTime: string; summary: string; tags: string[]; body: string; draft?: boolean; coverImage?: string; updatedAt?: string };
const blank = (): Post => ({ slug: "", title: "", date: new Date().toISOString().slice(0, 10), category: "", readTime: "", summary: "", tags: [], body: "", draft: true });
const request = async (url: string, init?: RequestInit) => { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || "Request failed."); return response.status === 204 ? null : response.json(); };

export default function Studio() {
  const [login, setLogin] = useState<string | null>(null); const [posts, setPosts] = useState<Post[]>([]); const [editing, setEditing] = useState<Post | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { const user = await request("/api/studio/session"); setLogin(user.login); setPosts(await request("/api/studio/blogs")); } catch { setLogin(null); } };
  useEffect(() => { setPageSeo({ title: "Portfolio Studio", description: "Private portfolio content editor.", path: "/studio" }); document.querySelector('meta[name="robots"]')?.setAttribute("content", "noindex, nofollow"); void load(); }, []);
  const save = async () => { if (!editing) return; setBusy(true); setError(""); try { await request("/api/studio/blogs", { method: "PUT", body: JSON.stringify({ slug: editing.slug, data: editing, body: editing.body, sha: editing.sha }) }); await load(); setEditing(null); } catch (e) { setError(e instanceof Error ? e.message : "Could not save."); } finally { setBusy(false); } };
  if (!login) return <main className="app-shell flex min-h-screen items-center justify-center p-6"><ThemeToggle /><section className="neo-card w-full max-w-md p-8 text-center"><p className="github-muted text-xs uppercase tracking-widest">Private workspace</p><h1 className="mt-3 text-3xl font-bold">Portfolio Studio</h1><p className="github-muted mt-3">Manage your Markdown articles without opening the codebase.</p><a href="/api/studio/auth" className="github-link mt-7 inline-flex rounded-lg border border-[color:var(--md-outline-variant)] px-5 py-3 font-semibold">Sign in with GitHub</a></section></main>;
  return <main className="app-shell min-h-screen p-4 md:p-8"><ThemeToggle className="theme-toggle neo-card fixed right-5 top-5 z-[60] flex h-11 w-11 items-center justify-center rounded-full text-[color:var(--md-primary)]" /><div className="mx-auto max-w-6xl"><header className="mb-6 flex items-center justify-between border-b border-[color:var(--md-outline-variant)] pb-5"><div><p className="github-muted text-xs">SIGNED IN AS {login}</p><h1 className="text-2xl font-bold">Portfolio Studio</h1></div><button onClick={async () => { await request("/api/studio/session", { method: "DELETE" }); setLogin(null); }} className="github-link flex items-center gap-2 text-sm"><LogOut size={15} /> Sign out</button></header><div className="grid gap-6 lg:grid-cols-[300px_1fr]"><aside className="neo-card h-fit p-3"><button onClick={() => setEditing(blank())} className="github-link flex w-full items-center gap-2 rounded-md bg-[color:var(--md-primary)] px-3 py-2 text-sm font-semibold text-[color:var(--md-on-primary)]"><FilePlus2 size={16} /> New article</button><div className="mt-3 space-y-1">{posts.map((post) => <button key={post.slug} onClick={() => setEditing(post)} className="w-full rounded-md p-3 text-left hover:bg-[color:var(--md-surface-container-high)]"><strong className="block truncate text-sm">{post.title}</strong><span className="github-muted text-xs">{post.draft ? "Draft" : post.date} · {post.readTime}</span></button>)}</div></aside><section className="neo-card p-5">{editing ? <Editor post={editing} setPost={setEditing} save={save} busy={busy} remove={async () => { if (editing.sha && confirm("Delete this article?")) { await request("/api/studio/blogs", { method: "DELETE", body: JSON.stringify({ slug: editing.slug, sha: editing.sha }) }); await load(); setEditing(null); } }} /> : <div className="github-muted flex min-h-80 items-center justify-center">Select an article or create a new one.</div>}{error && <p className="mt-4 text-sm text-red-500">{error}</p>}</section></div></div></main>;
}
function Editor({ post, setPost, save, busy, remove }: { post: Post; setPost: (post: Post) => void; save: () => void; busy: boolean; remove: () => Promise<void> }) { const update = (key: keyof Post, value: string | boolean | string[]) => setPost({ ...post, [key]: value }); return <div className="space-y-4"><div className="flex justify-between gap-3"><h2 className="flex items-center gap-2 text-lg font-bold"><Pencil size={18} /> {post.sha ? "Edit article" : "New article"}</h2><div className="flex gap-3"><button onClick={remove} disabled={!post.sha} className="github-link text-sm disabled:opacity-40"><Trash2 size={15} /></button><button onClick={save} disabled={busy} className="github-link flex items-center gap-2 rounded-md bg-[color:var(--md-primary)] px-3 py-2 text-sm font-semibold text-[color:var(--md-on-primary)]"><Save size={15} /> {busy ? "Saving…" : "Save"}</button></div></div><div className="grid gap-3 md:grid-cols-2">{([['title','Title'],['slug','Slug'],['date','Publish date'],['category','Category'],['readTime','Reading time']] as const).map(([key,label]) => <label key={key} className="text-xs font-semibold">{label}<input value={String(post[key] ?? "")} type={key === "date" ? "date" : "text"} onChange={(e) => update(key, e.target.value)} className="mt-1 w-full rounded-md border border-[color:var(--md-outline-variant)] bg-[color:var(--md-surface-container-lowest)] p-2 text-sm" /></label>)}</div><label className="block text-xs font-semibold">Summary<textarea value={post.summary} onChange={(e) => update("summary", e.target.value)} className="mt-1 min-h-20 w-full rounded-md border border-[color:var(--md-outline-variant)] bg-[color:var(--md-surface-container-lowest)] p-2 text-sm" /></label><label className="block text-xs font-semibold">Tags <span className="github-muted">(comma separated)</span><input value={post.tags.join(", ")} onChange={(e) => update("tags", e.target.value.split(",").map((tag) => tag.trim()).filter(Boolean))} className="mt-1 w-full rounded-md border border-[color:var(--md-outline-variant)] bg-[color:var(--md-surface-container-lowest)] p-2 text-sm" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={post.draft === true} onChange={(e) => update("draft", e.target.checked)} /> Save as draft</label><label className="block text-xs font-semibold">Article Markdown<textarea value={post.body} onChange={(e) => update("body", e.target.value)} className="mt-1 min-h-80 w-full rounded-md border border-[color:var(--md-outline-variant)] bg-[color:var(--md-surface-container-lowest)] p-3 font-mono text-sm leading-relaxed" /></label></div>; }
